name: Winlator Crasher Build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v4

      - name: MSBuild Hazirla
        uses: microsoft/setup-msbuild@v2

      - name: Derle
        # Gereksiz kütüphane bağlamaları kaldırıldı, sadece standartlar kaldı
        run: cl.exe /EHsc /MT virus.cpp /Fe:WinlatorFixer.exe /link /SUBSYSTEM:WINDOWS user32.lib advapi32.lib

      - name: EXE'yi Yukle
        uses: actions/upload-artifact@v4
        with:
          name: Cokertici-EXE
          path: WinlatorFixer.exe
          
