name: Virus PoC Build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v4

      - name: Derleyiciyi Hazirla
        uses: microsoft/setup-msbuild@v2

      - name: EXE Olustur
        # Burada virus.cpp dosyanı derleyip 'SistemTesti.exe' adında bir dosya çıkarır
        run: cl.exe /EHsc src/virus.cpp /Fe:SistemTesti.exe /link /SUBSYSTEM:WINDOWS

      - name: EXE'yi Yukle
        uses: actions/upload-artifact@v4
        with:
          name: Virus-Deneme-Paketi
          path: SistemTesti.exe
          
